# -*- coding: utf-8 -*-
"""only_one_data_학습.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2cXZwml6a37m3XL_DBSosKJ1bVqZWrp
"""

# ✅ 1. YOLOv8 설치
!pip install ultralytics --upgrade -q

# ✅ 2. 구글 드라이브 연동
from google.colab import drive
drive.mount('/content/drive')

# ✅ 3. ZIP 압축 해제 (경로에 맞게 수정)
!unzip -q "/content/car-damage-detector-main.zip" -d /content
!unzip -q "/content/3rd_gathering.zip" -d /content


# ✅ 실제 경로 확인
!ls /content/3rd_gathering/images/val_image | head -n 5

# ✅ 4. YAML 경로 지정
DATA_YAML_PATH = '/content/3rd_gathering/data.yaml'

!mv /content/3rd_gathering/labels/train_txt /content/3rd_gathering/labels/train_image
!mv /content/3rd_gathering/labels/val_txt /content/3rd_gathering/labels/val_image

import os

# ✅ 1. 폴더가 없으면 생성
os.makedirs('/content/3rd_gathering', exist_ok=True)

yaml_content = """
train: /content/3rd_gathering/images/train_image
val: /content/3rd_gathering/images/val_image
nc: 2
names: ['Breakage', 'Scratched']
"""

with open('/content/3rd_gathering/data.yaml', 'w') as f:
    f.write(yaml_content)

# ✅ 5. YOLOv8 모델 학습
from ultralytics import YOLO
model = YOLO('yolov8n.pt')  # 또는 'yolov8s.pt', 'yolov8m.pt'

model.train(
    data='/content/3rd_gathering/data.yaml',
    epochs=1,
    imgsz=800,
    batch=16,
    name='car_damage_v2',
    fliplr=0.5,
    flipud=0.1,
    hsv_h=0.05,
    hsv_s=0.5,
    hsv_v=0.3,
    mosaic=1.0,
    erasing=0.2,
    copy_paste=0.05  # 줄임
)

# ✅ 6. 라벨 파일 잘 읽히는지 확인
!ls /content/3rd_gathering/labels/val_image | head -n 10

!zip -r /content/runs_detect.zip /content/runs/detect

#only_for_breakage

#from google.colab import files
#files.download('/content/runs_detect.zip')

!find . -name "custom.py"